version: '3.8'
services:
  client:
    build:
        dockerfile: Dockerfile
        context: ./client
    image: nanosync/simplewebserver-client:1.0
    volumes:
        - ./client/public:/usr/share/nginx/html
    container_name: client
    ports:
      - 3000:3000
    restart: unless-stopped
  server:
    build:
        dockerfile: Dockerfile
        context: ./server
    image: nanosync/simplewebserver-server:1.0
    volumes:
        - /app/node_modules
        - ./server:/app
    container_name: server
    ports:
      - 4000:4000
    restart: unless-stopped
  reverseproxy:
    build:
      dockerfile: Dockerfile
      context: ./reverseproxy
    image: nanosync/simplewebserver-reverseproxy:1.0
    volumes:
      - ./reverseproxy/default.conf:/etc/nginx/conf.d/default.conf
    container_name: reverseproxy
    ports:
      - 80:80
    restart: always
    depends_on:
      - client
      - server